### PR TITLE
Created function check_valid_image in utils.py to validate images for…

### PR DESCRIPTION
**Pull request by ianc125**
… allowed extensions

### CODE REVIEW

**Comment by hmhrex** [comment]
This looks perfect! Thanks!

**Comment by hmhrex** [comment]
@ianc125, I've been meaning to ask, would you like commit access so that you can work on Tenma a little easier? Do you want me to assign issues to you? You seem to have a similar work style to me, and I could use the extra help :)

**Comment by ianc125** [comment]
@hmhrex Just saw this now, I would love commit access, but wont be able to be of much immediate help, kind of swamped at work and just moved a week ago so still getting situated. I am not super proficient with python, but can manage for the most part. Our style of coding is the same though that I noticed looking through the Tenma files. Love the project though and am definitely hoping this comes out on top as the best comic reader by far.

**Comment by hmhrex** [comment]
@ianc125 No problem! I completely understand. Thanks for the support and kind words!

**Pull request merged**
